version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test-client:
    docker:
      - image: circleci/node:10.16.3
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd client && npm install
            # - run: cd client && npm test
  build-and-test-server:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/postgres:9
        environment: DATABASE_URI=postgres://postgres:postgres@postgres:5432/facerecognition?sslmode=disable
      - image: circleci/redis:3.2
        environment: REDIS_HOST='127.0.01'
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd server && npm install
workflows:
  build-and-test:
    jobs:
      - build-and-test-client
      - build-and-test-server
