version: 2.1
jobs:
  build-and-test-client:
    docker:
      - image: circleci/node:10.16.3
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
              command: npm install
              working_directory: ../client
            - run:
              command: npm test
              working_directory: ../client
  build-and-test-server:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/postgres:8.0
      - image: circleci/redis:3.0
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
              command: npm install
              working_directory: ../server
            - run:
              command: npm test
              working_directory: ../server
workflows:
  build-and-test-client:
    jobs:
      - build-and-test-client
  build-and-test-server:
    jobs:
      - build-and-test-server
