version: "3.7"

services:
  #Backend api
  server:
    container_name: server
    build: ./
    command: npm run db
    working_dir: /user/src/server
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    volumes:
      - ./:/user/src/server
    environment:
      DATABASE_URI: postgres://admin:postgres-password@postgres:5432/facerecognition
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis

  # PostgreSQL database
  postgres:
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres-password
      POSTGRES_DB: facerecognition
      POSTGRES_HOST: postgres
    image: postgres
    ports:
      - "5432:5432"

  # Redis
  redis:
    image: redis
    container_name: "cache"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
